spring:
  application:
    name: twiggle
  data:
    mongodb:
      uri: mongodb+srv://mongodbadmin:sol@acedbadm!n@backend-cluster.qcxwk.mongodb.net/myDatabase?retryWrites=true&w=majority
server:
  port: 8080
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus,metrics'
      base-path: '/actuator'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: '${spring.application.name}'
  tracing:
    enabled: false
    sampling:
      probability: 1
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  use-management-port: false
