spring:
  application:
    name: twiggle
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      auto-index-creation: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
      base-path: '/actuator'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: false 