spring:
  application:
    name: twiggle
server:
  port: 80

# Actuator Configuration
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: "${spring.application.name}"
  tracing:
    enabled: false
    sampling:
      probability: 1.0

# Springdoc Configuration
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  use-management-port: false

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
