services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - monitoring-network
    depends_on:
      - mongodb
    env_file:
      - ../.env
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/twiggle

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - monitoring-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  monitoring-network:
    driver: bridge