version: '3.8'
services:
  app-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SKIP_TESTS: "false"
        ENV: "test"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-test:27017/test
      - RUN_INTEGRATION_TESTS=true
    depends_on:
      mongodb-test:
        condition: service_healthy
    networks:
      - test-network

  mongodb-test:
    image: mongo:7.0.5
    container_name: mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - test-network

volumes:
  mongodb_test_data:
    driver: local

networks:
  test-network:
    driver: bridge 