INSERT INTO plant_diseases (
    common_name,
    scientific_name,
    description,
    symptoms,
    favorable_conditions,
    prevention_tips,
    organic_control,
    chemical_control,
    image_url,
    transmission_method,
    contagiousness,
    severity_rating,
    time_to_onset,
    recovery_chances
) VALUES
-- Downy Mildew
('Downy Mildew',
 'Peronospora spp.',
 'A fungal-like disease causing yellow or pale green spots on upper leaf surfaces and grayish mold on undersides.',
 'Yellow spots on upper leaf surfaces; grayish mold on undersides; leaf curling and distortion.',
 'Cool, moist conditions with poor air circulation.',
 'Ensure proper spacing and air circulation; use drip irrigation to keep foliage dry.',
 'Apply neem oil or a milk-water spray (3:10 ratio) as preventive measures.',
 'Use fungicides containing chlorothalonil or copper-based compounds early in disease development.',
 'https://www.planetnatural.com/wp-content/uploads/2012/12/downy-mildew-disease-920x518.webp',
 'Airborne spores',
 'High',
 'Moderate',
 '5-7 days after infection',
 'Moderate if treated early'),

-- Early Blight
('Early Blight',
 'Alternaria solani',
 'A common fungal disease in tomatoes and potatoes, leading to leaf spots and fruit rot.',
 'Dark brown spots with concentric rings on lower leaves; yellowing and defoliation; fruit lesions near stem.',
 'Warm, humid conditions; presence of infected plant debris.',
 'Rotate crops every 2-3 years; remove and destroy infected plant material.',
 'Apply compost tea or neem oil as preventive sprays.',
 'Use fungicides containing chlorothalonil or copper; apply at first sign of disease.',
 'https://gardeningcalendar.ca/wp-content/uploads/2023/06/Alternarioza_ziemniaka_ilustr-scaled-1.webp',
 'Soil-borne and airborne spores',
 'High',
 'Severe',
 '7-10 days after infection',
 'Low if not managed promptly'),

-- Fusarium Wilt
('Fusarium Wilt',
 'Fusarium oxysporum',
 'A soil-borne fungal disease causing wilting and yellowing of plants, often leading to death.',
 'Yellowing of lower leaves; wilting during the day; brown discoloration in vascular tissue.',
 'Warm soil temperatures; presence of the pathogen in soil.',
 'Use resistant plant varieties; practice crop rotation; sterilize tools and equipment.',
 'Incorporate beneficial microbes like Trichoderma into the soil.',
 'Limited chemical control; soil fumigation may reduce pathogen levels.',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/500px-Fusarium_wilt_symptom_tobacco.jpg',
 'Soil-borne',
 'Moderate',
 'Severe',
 '14-21 days after infection',
 'Low; plants often do not recover'),

-- Root Rot
('Root Rot',
 'Phytophthora spp., Pythium spp.',
 'A disease caused by various pathogens leading to decay of plant roots, often due to overwatering.',
 'Wilting despite moist soil; yellowing leaves; mushy, brown roots.',
 'Poorly drained soils; overwatering; high humidity.',
 'Ensure proper drainage; avoid overwatering; use well-aerated soil mixes.',
 'Apply beneficial fungi like Trichoderma to suppress pathogens.',
 'Use fungicides containing mefenoxam or phosphonates as soil drenches.',
 'https://welovetropicalplants.com/a/blog/media/tropicaluniqueplants.myshopify.com/Post/featured_img/root-rot_(5).jpg',
 'Soil-borne',
 'Moderate',
 'Severe',
 'Varies; symptoms may appear over weeks',
 'Moderate if caught early and conditions are corrected'),

-- Leaf Spot
('Leaf Spot',
 'Cercospora spp., Septoria spp.',
 'A group of diseases causing spots on foliage, leading to premature leaf drop.',
 'Brown or black spots on leaves; yellow halos; premature defoliation.',
 'High humidity; overcrowded plantings; overhead watering.',
 'Space plants appropriately; water at the base; remove infected leaves.',
 'Apply compost teas or copper-based sprays as preventive measures.',
 'Use fungicides like chlorothalonil or mancozeb at first sign of disease.',
 'https://www.cardinallawns.com/wp-content/uploads/2018/04/leaf-spots-1024x1024.jpg',
 'Airborne spores and splashing water',
 'Moderate',
 'Moderate',
 '7-14 days after infection',
 'High with proper management'),

-- Powdery Mildew
('Powdery Mildew',
 'Erysiphe spp., Podosphaera spp.',
 'A fungal disease characterized by white powdery growth on leaves and stems.',
 'White or gray powdery spots on leaves; distorted growth; premature leaf drop.',
 'Warm days and cool nights; high humidity; poor air circulation.',
 'Ensure good air circulation; avoid overhead watering; plant resistant varieties.',
 'Apply sulfur sprays or neem oil at first sign of disease.',
 'Use fungicides containing myclobutanil or propiconazole as needed.',
 'https://www.gardendesign.com/pictures/images/400x320Exact_0x0/site_3/powdery-mildew-powdery-mildew-on-squash-leaf-shutterstock-com_13365.jpg',
 'Airborne spores',
 'High',
 'Moderate',
 '3-7 days after infection',
 'High with timely treatment'),

-- Rust
('Rust',
 'Puccinia spp.',
 'A fungal disease causing rust-colored pustules on leaves and stems.',
 'Orange, yellow, or brown pustules on undersides of leaves; leaf distortion; defoliation.',
 'Moist conditions; overcrowded plants; poor air circulation.',
 'Remove and destroy infected leaves; improve air circulation; avoid overhead watering.',
 'Apply sulfur or copper-based sprays as preventive measures.',
 'Use fungicides like chlorothalonil or myclobutanil at first sign of disease.',
 'https://cdn.britannica.com/61/185161-050-C7424B2A/spots-Orange-cedar-apple-rust-disease-apple-leaf.jpg',
 'Airborne spores',
 'High',
 'Moderate',
 '7-10 days after infection',
 'High with appropriate control measures'),

-- Black Spot
('Black Spot',
 'Diplocarpon rosae',
 'A fungal disease primarily affecting roses, leading to black spots on leaves.',
 'Black spots with fringed margins on leaves; yellowing; premature leaf drop.',
 'Warm, humid conditions; water splashing on foliage.',
 'Plant resistant varieties; ensure good air circulation; remove fallen leaves.',
 'Apply neem oil or baking soda sprays regularly.',
 'Use fungicides containing chlorothalonil or mancozeb every 7-14 days during growing season.',
 'https://www.gardentech.com/-/media/project/oneweb/gardentech/images/pest-id/plant-pest/black-spot/close-up-of-black-spot.jpg',
 'Airborne spores and splashing water',
 'High',
 'Moderate',
 '10-14 days after infection',
 'High with consistent treatment'),

 --Leaf Tip Burn
 (
    'Leaf Tip Burn',
    'Physiological disorder (not caused by pathogens)',
    'A condition where leaf tips turn brown due to environmental stress or nutrient imbalance.',
    'Brown, necrotic tips on leaves; may progress inward if severe.',
    'Inconsistent watering; low humidity; calcium deficiency.',
    'Maintain consistent soil moisture; ensure adequate calcium levels; avoid over-fertilization.',
    'Improve watering practices; use calcium-rich amendments if needed.',
    'Not applicable; chemical treatments are ineffective.',
    'https://ipm.missouri.edu/meg/2021/1/leafTipburn-DT/FluorideToxicity.jpg',
    'Not applicable',
    'Low',
    'Mild',
    'Gradual onset over days to weeks',
    'High with corrective measures'
),

--Leaf Drop
(
    'Leaf Drop',
    'Physiological response (various causes)',
    'Leaf drop is a symptom of various stressors, including environmental changes, improper watering, pests, or diseases.',
    'Sudden or gradual loss of leaves; may be accompanied by yellowing or browning.',
    'Environmental stressors such as temperature fluctuations, overwatering, underwatering, low humidity, or pest infestations.',
    'Maintain stable environmental conditions; proper watering; monitor for pests and diseases.',
    'Adjust care practices to address the underlying cause; ensure appropriate light, water, and humidity levels.',
    'Depends on the underlying cause; fungicides or insecticides may be used if pests or diseases are involved.',
    'https://www.pennington.com//-/media/Project/OneWeb/Pennington/Images/blog/fertilizer/why-is-my-plant-dropping-leaves/leaves-dropping-h.jpg',
    'Varies (e.g., pests, pathogens, environmental factors)',
    'Variable',
    'Variable',
    'Varies depending on cause',
    'High if underlying issue is resolved'
);
