INSERT INTO plants_library (
    common_name,
    other_name,
    scientific_name,
    short_description,
    origin,
    plant_type,
    climate,
    life_cycle,
    watering_frequency,
    soil_type,
    size,
    sunlight_requirement,
    growth_rate,
    ideal_place,
    care_level,
    image_url,
    best_planting_season,
    gardening_tips,
    pruning_guide,
    seed_depth,
    germination_time,
    time_to_harvest,
    flower,
    fruit,
    medicinal,
    temperature_range,
    common_pests,
    common_diseases,
    companion_plants,
    avoid_planting_with,
    pest_disease_prevention_tips,
    cool_facts,
    edible_parts
) VALUES
-- 1. Basil
(
    'Basil',
    'Sweet Basil',
    'Ocimum basilicum',
    'A fragrant herb commonly used in cooking, especially in Italian cuisine.',
    'India',
    'Herb',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Small',
    'Full Sun',
    'Fast',
    'Kitchen windowsill, balcony',
    'Easy',
    'https://images.unsplash.com/photo-1610970884954-4d376ecba53f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHwxLiUyMEJhc2lsfGVufDB8fHx8MTc0NTIyMTEyMnww&ixlib=rb-4.0.3&q=80&w=1080',
    'Spring',
    'Pinch off flower buds to encourage leaf growth.',
    'Prune regularly',
    0.6,
    7,
    60,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 35),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Downy mildew'],
    ARRAY['Tomato', 'Oregano'],
    ARRAY['Rue'],
    ARRAY['Ensure good air circulation and avoid overhead watering.'],
    ARRAY['Basil is considered a symbol of love in Italy.'],
    ARRAY['Leaves']
),
-- 2. Cherry Tomato
(
    'Cherry Tomato',
    'Tomato',
    'Solanum lycopersicum var. cerasiforme',
    'A small, sweet tomato variety perfect for container gardening.',
    'South America',
    'Vegetable',
    'Temperate',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Balcony, rooftop garden',
    'Moderate',
    'https://images.unsplash.com/photo-1570543375343-63fe3d67761b?q=80&w=2676&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Provide support with stakes or cages.',
    'Prune to shape',
    1.0,
    7,
    75,
    TRUE,
    TRUE,
    FALSE,
    numrange(18, 30),
    ARRAY['Tomato hornworm', 'Aphids'],
    ARRAY['Early blight', 'Fusarium wilt'],
    ARRAY['Basil', 'Marigold'],
    ARRAY['Potato'],
    ARRAY['Rotate crops annually to prevent soil-borne diseases.'],
    ARRAY['Rich in lycopene, an antioxidant.'],
    ARRAY['Fruits']
),
-- 3. Lavender
(
    'Lavender',
    'English Lavender',
    'Lavandula angustifolia',
    'A fragrant flowering plant known for its calming scent and purple blooms.',
    'Mediterranean',
    'Shrub',
    'Mediterranean',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Patio, garden border',
    'Easy',
    'https://images.unsplash.com/photo-1620005807545-2e08850d6591?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Avoid overwatering; prefers dry conditions.',
    'Prune after bloom',
    0.3,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 30),
    ARRAY['Spittlebugs'],
    ARRAY['Root rot'],
    ARRAY['Rosemary', 'Sage'],
    ARRAY['Mint'],
    ARRAY['Ensure well-drained soil to prevent root diseases.'],
    ARRAY['Used in aromatherapy for relaxation.'],
    ARRAY['Flowers']
),
-- 4. Snake Plant
(
    'Snake Plant',
    'Mother-in-law''s Tongue',
    'Sansevieria trifasciata',
    'A hardy indoor plant known for its upright, sword-like leaves.',
    'West Africa',
    'Succulent',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Partial Shade',
    'Slow',
    'Living room, bedroom',
    'Easy',
    'https://vgrgardens.com/wp-content/uploads/2024/08/Screenshot-2024-08-22-144950.png',
    'Spring',
    'Allow soil to dry between waterings.',
    'No pruning required',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    TRUE,
    numrange(15, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['ZZ Plant', 'Pothos'],
    ARRAY['Overwatering'],
    ARRAY['Use well-draining soil to prevent root rot.'],
    ARRAY['NASA listed it as an air-purifying plant.'],
    ARRAY['None']
),
-- 5. Aloe Vera
(
    'Aloe Vera',
    'Medicinal Aloe',
    'Aloe barbadensis miller',
    'A succulent plant known for its soothing gel used in skincare.',
    'Arabian Peninsula',
    'Succulent',
    'Arid',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Full Sun',
    'Slow',
    'Balcony, kitchen',
    'Easy',
    'https://costafarms.com/cdn/shop/files/DSC0363--cream.jpg?v=1730831876',
    'Spring',
    'Place in bright, indirect sunlight.',
    'No pruning required',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids'],
    ARRAY['Leaf spot'],
    ARRAY['Cactus', 'Succulents'],
    ARRAY['Overwatering'],
    ARRAY['Use pots with drainage holes to prevent waterlogging.'],
    ARRAY['Gel is used to treat burns and cuts.'],
    ARRAY['Leaves']
),
-- 6. Marigold
(
    'Marigold',
    'Pot Marigold',
    'Calendula officinalis',
    'Brightly colored flowers that repel pests and attract pollinators.',
    'Southern Europe',
    'Flower',
    'Temperate',
    'Annual',
    'Moderate',
    'Loamy',
    'Small',
    'Full Sun',
    'Fast',
    'Garden beds, borders',
    'Easy',
    'https://images.unsplash.com/photo-1620005807545-2e08850d6591?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Deadhead spent blooms to encourage continuous flowering.',
    'Prune regularly',
    0.6,
    5,
    60,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 30),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Powdery mildew'],
    ARRAY['Tomato', 'Basil'],
    ARRAY['Beans'],
    ARRAY['Ensure proper spacing to reduce humidity and prevent fungal diseases.'],
    ARRAY['Marigolds are often used in cultural festivals and ceremonies.'],
    ARRAY['Petals']
),
-- 7. Mint
(
    'Mint',
    'Spearmint',
    'Mentha spicata',
    'A fast-growing herb known for its refreshing aroma and flavor.',
    'Europe',
    'Herb',
    'Temperate',
    'Perennial',
    'High',
    'Loamy',
    'Small',
    'Partial Shade',
    'Fast',
    'Kitchen garden, containers',
    'Easy',
    'https://images.unsplash.com/photo-1618130070080-91f4d55a2383?q=80&w=2362&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Regularly trim to prevent flowering and encourage bushy growth.',
    'Prune regularly',
    0.5,
    10,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids', 'Flea beetles'],
    ARRAY['Rust', 'Powdery mildew'],
    ARRAY['Cabbage', 'Tomato'],
    ARRAY['Parsley'],
    ARRAY['Plant in containers to prevent invasive spreading.'],
    ARRAY['Mint is a natural insect repellent.'],
    ARRAY['Leaves']
),
-- 8. Money Plant
(
    'Money Plant',
    'Devil''s Ivy',
    'Epipremnum aureum',
    'A popular indoor plant believed to bring prosperity and good luck.',
    'Southeast Asia',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Low',
    'Loamy',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Living room, office',
    'Easy',
    'https://cdn.britannica.com/62/193862-050-4A7DBC6F/Parsley.jpg?w=300',
    'Spring',
    'Trim long vines to maintain desired shape and encourage growth.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Philodendron', 'Spider plant'],
    ARRAY['Direct sunlight'],
    ARRAY['Allow soil to dry between waterings to prevent root rot.'],
    ARRAY['Known for its air-purifying qualities.'],
    ARRAY['None']
),
-- 9. Rose
(
    'Rose',
    'Garden Rose',
    'Rosa spp.',
    'A classic flowering plant cherished for its beauty and fragrance.',
    'Asia',
    'Shrub',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Garden beds, borders',
    'Moderate',
    'https://images.unsplash.com/photo-1559563362-c667ba5f5480?q=80&w=2602&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Prune in late winter to promote healthy growth and blooms.',
    'Prune after bloom',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids', 'Japanese beetles'],
    ARRAY['Black spot', 'Powdery mildew'],
    ARRAY['Lavender', 'Marigold'],
    ARRAY['Garlic'],
    ARRAY['Ensure good air circulation and remove fallen leaves to prevent diseases.'],
    ARRAY['Roses have been symbols of love and beauty for centuries.'],
    ARRAY['Petals']
),
-- 10. Peace Lily
(
    'Peace Lily',
    'Spathiphyllum',
    'Spathiphyllum wallisii',
    'An elegant indoor plant known for its white blooms and air-purifying qualities.',
    'Americas',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Partial Shade',
    'Slow',
    'Living room, bathroom',
    'Easy',
    'https://images.unsplash.com/photo-1651909529901-d2221d3c953e?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Remove yellowing leaves and spent blooms to encourage new growth.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(18, 27),
    ARRAY['Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Ferns', 'Philodendron'],
    ARRAY['Direct sunlight'],
    ARRAY['Keep soil consistently moist but not waterlogged.'],
    ARRAY['Peace lilies can bloom twice a year under proper care.'],
    ARRAY['None']
),
-- 1. ZZ Plant
(
    'ZZ Plant',
    'Zanzibar Gem',
    'Zamioculcas zamiifolia',
    'A hardy indoor plant with glossy leaves, tolerant of low light and infrequent watering.',
    'Eastern Africa',
    'Shrub',
    'Tropical',
    'Perennial',
    'Low',
    'Loamy',
    'Medium',
    'Low Light',
    'Slow',
    'Office, living room',
    'Easy',
    'https://costafarms.com/cdn/shop/files/DSC0363--cream.jpg?v=1730831876',
    'Spring',
    'Allow soil to dry out between waterings to prevent root rot.',
    'No pruning required',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Snake Plant', 'Pothos'],
    ARRAY['Overwatering'],
    ARRAY['Use well-draining soil and avoid overwatering.'],
    ARRAY['Known for its air-purifying qualities.'],
    ARRAY['None']
),
-- 2. Spider Plant
(
    'Spider Plant',
    'Airplane Plant',
    'Chlorophytum comosum',
    'An easy-to-grow houseplant with arching leaves and baby plantlets.',
    'South Africa',
    'Herb',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Indirect Light',
    'Fast',
    'Hanging baskets, shelves',
    'Easy',
    'https://www.beardsanddaisies.co.uk/cdn/shop/products/Beards-Daises-27.9.220111copy_1080x.jpg?v=1664959425',
    'Spring',
    'Trim brown tips and remove plantlets to encourage growth.',
    'Prune regularly',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(13, 27),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Leaf tip burn'],
    ARRAY['Peace Lily', 'Philodendron'],
    ARRAY['Direct sunlight'],
    ARRAY['Avoid fluoride-rich water to prevent leaf tip burn.'],
    ARRAY['NASA listed it as an air-purifying plant.'],
    ARRAY['None']
),
-- 3. Jade Plant
(
    'Jade Plant',
    'Money Tree',
    'Crassula ovata',
    'A succulent with fleshy, oval leaves, symbolizing prosperity.',
    'South Africa',
    'Succulent',
    'Arid',
    'Perennial',
    'Low',
    'Sandy',
    'Small',
    'Full Sun',
    'Slow',
    'Office desk, windowsill',
    'Easy',
    'https://westernstarnurseries.com/wp-content/uploads/2024/09/Crassula-Ovata-Jade-Plant.jpg',
    'Spring',
    'Allow soil to dry between waterings; avoid overwatering.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    TRUE,
    numrange(15, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Aloe Vera', 'Snake Plant'],
    ARRAY['Overwatering'],
    ARRAY['Use cactus soil mix for better drainage.'],
    ARRAY['Considered a symbol of good luck.'],
    ARRAY['Leaves']
),
-- 4. Boston Fern
(
    'Boston Fern',
    'Sword Fern',
    'Nephrolepis exaltata',
    'A lush, arching fern ideal for hanging baskets and shaded areas.',
    'Tropical regions',
    'Groundcover',
    'Tropical',
    'Perennial',
    'High',
    'Peaty',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Bathrooms, shaded patios',
    'Moderate',
    'https://costafarms.com/cdn/shop/files/L-BOS-P-WMC-01-CF--white_411c64f6-cb73-419c-8204-eb2154c19b62.jpg?v=1707335297',
    'Spring',
    'Maintain high humidity and keep soil consistently moist.',
    'Prune regularly',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(16, 24),
    ARRAY['Spider mites'],
    ARRAY['Leaf drop'],
    ARRAY['Peace Lily', 'Calathea'],
    ARRAY['Direct sunlight'],
    ARRAY['Mist regularly to maintain humidity.'],
    ARRAY['Excellent natural air humidifier.'],
    ARRAY['None']
),
-- 5. Fiddle Leaf Fig
(
    'Fiddle Leaf Fig',
    'Banjo Fig',
    'Ficus lyrata',
    'A popular indoor tree with large, violin-shaped leaves.',
    'Western Africa',
    'Tree',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Bright Indirect Light',
    'Slow',
    'Living room corners',
    'Moderate',
    'https://gardengoodsdirect.com/cdn/shop/articles/planting_guide_banners.jpg?v=1637070918&width=830',
    'Spring',
    'Rotate regularly for even growth; avoid drafts.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Spider mites', 'Scale insects'],
    ARRAY['Leaf drop'],
    ARRAY['Rubber Plant', 'Snake Plant'],
    ARRAY['Cold drafts'],
    ARRAY['Wipe leaves to remove dust and allow photosynthesis.'],
    ARRAY['Adds a dramatic touch to interiors.'],
    ARRAY['None']
),
-- 6. Calathea
(
    'Calathea',
    'Prayer Plant',
    'Calathea spp.',
    'Known for its striking leaf patterns and movement in response to light.',
    'South America',
    'Herb',
    'Tropical',
    'Perennial',
    'High',
    'Peaty',
    'Medium',
    'Indirect Light',
    'Moderate',
    'Bedrooms, offices',
    'Moderate',
    'https://abeautifulmess.com/wp-content/uploads/2023/06/rubbertree-1-1122x1536.jpg',
    'Spring',
    'Maintain high humidity and avoid direct sunlight.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Spider mites'],
    ARRAY['Leaf spot'],
    ARRAY['Ferns', 'Peace Lily'],
    ARRAY['Direct sunlight'],
    ARRAY['Mist regularly to maintain humidity.'],
    ARRAY['Leaves close at night, resembling hands in prayer.'],
    ARRAY['None']
),
-- 7. Areca Palm
(
    'Areca Palm',
    'Butterfly Palm',
    'Dypsis lutescens',
    'A graceful palm with feathery fronds, ideal for indoor spaces.',
    'Madagascar',
    'Tree',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Bright Indirect Light',
    'Moderate',
    'Living room, office',
    'Moderate',
    'https://images.unsplash.com/photo-1506634064465-7dab4de896ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHwxNy4lMjBBcmVjYSUyMFBhbG18ZW58MHx8fHwxNzQ1MjIxMTQxfDA&ixlib=rb-4.0.3&q=80&w=1080',
    'Spring',
    'Keep soil moist but not soggy; avoid direct sunlight.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Spider mites'],
    ARRAY['Leaf tip burn'],
    ARRAY['Peace Lily', 'Snake Plant'],
    ARRAY['Cold drafts'],
    ARRAY['Wipe leaves to remove dust and allow photosynthesis.'],
    ARRAY['Known for its air-purifying qualities.'],
    ARRAY['None']
),
-- 8. Chili Pepper
(
    'Chili Pepper',
    'Hot Pepper',
    'Capsicum annuum',
    'A spicy fruit-bearing plant, great for container gardening.',
    'Central America',
    'Vegetable',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Balcony, rooftop garden',
    'Moderate',
    'https://images.unsplash.com/photo-1658898359490-e68fadbcfbf5?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Provide support as plants grow; harvest regularly to encourage production.',
    'Prune regularly',
    0.6,
    7,
    80,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Powdery mildew'],
    ARRAY['Basil', 'Marigold'],
    ARRAY['Fennel'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Capsaicin in peppers deters many pests.'],
    ARRAY['Fruits']
),
-- 9. Lemongrass
(
    'Lemongrass',
    'Cymbopogon',
    'Cymbopogon citratus',
    'A fragrant grass used in cooking and as a natural insect repellent.',
    'Southeast Asia',
    'Grass',
    'Tropical',
    'Perennial',
    'High',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Pots, balcony, rooftop beds',
    'Easy',
    'https://www.attainable-sustainable.net/wp-content/uploads/2021/03/lemongrass-plants.jpg',
    'Spring',
    'Trim regularly to encourage bushy growth.',
    'Prune regularly',
    1.0,
    10,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['None'],
    ARRAY['Rust'],
    ARRAY['Basil', 'Chives'],
    ARRAY['Shady plants'],
    ARRAY['Keep in sunny, well-drained spots.'],
    ARRAY['Lemongrass tea aids digestion.'],
    ARRAY['Stalks']
),
-- 10. Ponytail Palm
(
    'Ponytail Palm',
    'Elephant Foot Tree',
    'Beaucarnea recurvata',
    'A drought-tolerant plant with a swollen base and cascading leaves.',
    'Mexico',
    'Succulent',
    'Arid',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Bright Indirect Light',
    'Slow',
    'Living room, office',
    'Easy',
    'https://www.campbellsnursery.com/wp-content/uploads/2020/08/Palm-Ponytail.jpg',
    'Spring',
    'Allow soil to dry out completely between waterings.',
    'No pruning required',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Snake Plant', 'ZZ Plant'],
    ARRAY['Overwatering'],
    ARRAY['Use cactus soil mix for better drainage.'],
    ARRAY['Stores water in its bulbous trunk.'],
    ARRAY['None']
),
-- 1. Monstera Deliciosa
(
    'Monstera Deliciosa',
    'Swiss Cheese Plant',
    'Monstera deliciosa',
    'A popular indoor plant known for its large, perforated leaves.',
    'Central America',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Indirect Light',
    'Moderate',
    'Living room, office',
    'Moderate',
    'https://nurserynisarga.in/wp-content/uploads/2025/01/decore-img.webp',
    'Spring',
    'Provide support for climbing; wipe leaves to remove dust.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    TRUE,
    FALSE,
    numrange(18, 30),
    ARRAY['Mealybugs', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Philodendron', 'Pothos'],
    ARRAY['Direct sunlight'],
    ARRAY['Ensure well-draining soil to prevent root rot.'],
    ARRAY['Leaves develop holes as they mature.'],
    ARRAY['Fruits']
),
-- 1. Swiss Chard
(
    'Swiss Chard',
    'Silverbeet',
    'Beta vulgaris subsp. vulgaris',
    'A leafy green vegetable known for its colorful stems and nutritious leaves.',
    'Mediterranean',
    'Vegetable',
    'Temperate',
    'Biennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Balcony, kitchen garden',
    'Easy',
    'https://bonnieplants.com/cdn/shop/products/031122_T118630_202001_Bonnie_Swiss-Chard_ALT_02.jpg?v=1653335111&width=2048',
    'Spring',
    'Harvest outer leaves regularly to encourage new growth.',
    'Prune regularly',
    1.0,
    7,
    60,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids', 'Leaf miners'],
    ARRAY['Downy mildew'],
    ARRAY['Carrots', 'Onions'],
    ARRAY['Potatoes'],
    ARRAY['Rotate crops annually to prevent soil-borne diseases.'],
    ARRAY['Rich in vitamins A, C, and K.'],
    ARRAY['Leaves']
),
-- 2. Nasturtium
(
    'Nasturtium',
    'Tropaeolum',
    'Tropaeolum majus',
    'A vibrant flowering plant with edible leaves and flowers, known for its peppery flavor.',
    'South America',
    'Flower',
    'Temperate',
    'Annual',
    'Low',
    'Sandy',
    'Small',
    'Full Sun',
    'Fast',
    'Hanging baskets, borders',
    'Easy',
    'https://b1387267.smushcdn.com/1387267/wp-content/uploads/2024/05/IMG_20210623_nasturtium-1152x1536.jpg?lossy=1&strip=1&webp=1',
    'Spring',
    'Deadhead spent flowers to prolong blooming.',
    'Prune regularly',
    1.5,
    10,
    60,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids'],
    ARRAY['None'],
    ARRAY['Cabbage', 'Radish'],
    ARRAY['None'],
    ARRAY['Plant with marigolds to deter pests.'],
    ARRAY['Acts as a trap crop for aphids, protecting other plants.'],
    ARRAY['Leaves', 'Flowers']
),
-- 3. Lemon Balm
(
    'Lemon Balm',
    'Melissa',
    'Melissa officinalis',
    'A fragrant herb with lemon-scented leaves, used in teas and aromatherapy.',
    'Southern Europe',
    'Herb',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Partial Shade',
    'Moderate',
    'Herb garden, containers',
    'Easy',
    'https://gardeningsg.nparks.gov.sg/images/Plants/Radish_JacChua%20(1).jpg',
    'Spring',
    'Trim regularly to prevent flowering and encourage bushy growth.',
    'Prune regularly',
    0.5,
    7,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Basil', 'Chives'],
    ARRAY['None'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Attracts bees and beneficial insects.'],
    ARRAY['Leaves']
),
-- 4. Thyme
(
    'Thyme',
    'Common Thyme',
    'Thymus vulgaris',
    'A low-growing herb known for its aromatic leaves, used in cooking and medicine.',
    'Mediterranean',
    'Herb',
    'Mediterranean',
    'Perennial',
    'Low',
    'Sandy',
    'Small',
    'Full Sun',
    'Slow',
    'Rock gardens, containers',
    'Easy',
    'https://victoriananursery.co.uk//images/800/sq-thyme-002.jpg',
    'Spring',
    'Prune after flowering to maintain shape and encourage new growth.',
    'Prune after bloom',
    0.5,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 30),
    ARRAY['Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Cabbage', 'Strawberries'],
    ARRAY['None'],
    ARRAY['Avoid overwatering; prefers dry conditions.'],
    ARRAY['Thyme has antiseptic properties and is used in natural remedies.'],
    ARRAY['Leaves']
),
-- 5. Blueberry
(
    'Blueberry',
    'Highbush Blueberry',
    'Vaccinium corymbosum',
    'A fruit-bearing shrub producing sweet, nutritious berries.',
    'North America',
    'Shrub',
    'Temperate',
    'Perennial',
    'Moderate',
    'Peaty',
    'Medium',
    'Full Sun',
    'Slow',
    'Containers, garden beds',
    'Moderate',
    'https://m.media-amazon.com/images/I/61obdv2w81L._AC_US750_.jpg',
    'Spring',
    'Prune annually to remove old wood and encourage new growth.',
    'Prune after bloom',
    1.0,
    21,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Birds', 'Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Azaleas', 'Rhododendrons'],
    ARRAY['Tomatoes'],
    ARRAY['Use acidic soil and mulch to retain moisture.'],
    ARRAY['Rich in antioxidants and vitamins.'],
    ARRAY['Fruits']
),
-- 7. Rosemary
(
    'Rosemary',
    'Rosmarinus',
    'Salvia rosmarinus',
    'An evergreen herb with needle-like leaves, used in cooking and aromatherapy.',
    'Mediterranean',
    'Shrub',
    'Mediterranean',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Full Sun',
    'Slow',
    'Containers, herb gardens',
    'Easy',
    'https://vgrgardens.com/wp-content/uploads/2024/08/Screenshot-2024-08-22-144950.png',
    'Spring',
    'Prune after flowering to maintain shape and encourage new growth.',
    'Prune after bloom',
    0.5,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 30),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Sage', 'Thyme'],
    ARRAY['Basil'],
    ARRAY['Ensure well-drained soil to prevent root diseases.'],
    ARRAY['Rosemary has antiseptic properties and is used in natural remedies.'],
    ARRAY['Leaves']
),
-- 10. Parsley
(
    'Parsley',
    'Garden Parsley',
    'Petroselinum crispum',
    'A versatile herb used as a garnish and flavoring in various cuisines.',
    'Mediterranean',
    'Herb',
    'Temperate',
    'Biennial',
    'Moderate',
    'Loamy',
    'Small',
    'Partial Shade',
    'Moderate',
    'Kitchen garden, containers',
    'Easy',
    'https://cdn.britannica.com/62/193862-050-4A7DBC6F/Parsley.jpg?w=300',
    'Spring',
    'Harvest outer leaves regularly to encourage new growth.',
    'Prune regularly',
    0.5,
    14,
    70,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Aphids'],
    ARRAY['Leaf spot'],
    ARRAY['Tomatoes', 'Carrots'],
    ARRAY['Lettuce'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Rich in vitamins A, C, and K.'],
    ARRAY['Leaves']
),
-- 6. Agapanthus
(
    'Agapanthus',
    'Lily of the Nile',
    'Agapanthus africanus',
    'A perennial plant with striking blue or white flower clusters.',
    'South Africa',
    'Flower',
    'Mediterranean',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Containers, borders',
    'Easy',
    'https://hartley-botanic.co.uk/wp-content/uploads/2017/06/Agapanthus-Northern-Star-2-Aug-12-June-2017-767x1023.jpg',
    'Spring',
    'Divide clumps every few years for better flowering.',
    'Prune after bloom',
    1.0,
    21,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['Snails'],
    ARRAY['Root rot'],
    ARRAY['Daylilies', 'Lavender'],
    ARRAY['Heavy water-demanding plants'],
    ARRAY['Avoid overwatering; thrives in well-drained soil.'],
    ARRAY['Often planted en masse for a striking landscape.'],
    ARRAY['None']
),
-- 7. Bamboo Palm
(
    'Bamboo Palm',
    'Reed Palm',
    'Chamaedorea seifrizii',
    'An attractive palm ideal for indoor settings with low light.',
    'Central America',
    'Grass',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Indirect Light',
    'Slow',
    'Living rooms, offices',
    'Easy',
    'https://www.capegardencentre.co.za/cdn/shop/products/35L-dypsis-lutescens-onlineshop-capegarden_1080x.jpg?v=1738754850',
    'Spring',
    'Trim dead fronds to keep tidy.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 26),
    ARRAY['Spider mites'],
    ARRAY['Leaf tip burn'],
    ARRAY['ZZ Plant', 'Peace Lily'],
    ARRAY['Direct sunlight'],
    ARRAY['Clean leaves regularly to maintain health.'],
    ARRAY['Filters benzene and formaldehyde from air.'],
    ARRAY['None']
),
-- 8. Bottle Gourd
(
    'Bottle Gourd',
    'Calabash',
    'Lagenaria siceraria',
    'A fast-growing vegetable climber with edible fruits shaped like bottles.',
    'Africa/Asia',
    'Vegetable',
    'Tropical',
    'Annual',
    'High',
    'Loamy',
    'Large',
    'Full Sun',
    'Fast',
    'Rooftop trellis, garden fence',
    'Moderate',
    'https://cdn.britannica.com/00/122500-050-208253EC/Bottle-gourd.jpg?w=300',
    'Rainy/Monsoon',
    'Provide support and regular pruning to encourage more fruits.',
    'Prune regularly',
    2.0,
    7,
    90,
    TRUE,
    TRUE,
    TRUE,
    numrange(22, 35),
    ARRAY['Fruit flies', 'Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Beans', 'Corn'],
    ARRAY['Potatoes'],
    ARRAY['Spray neem oil as an organic pest control.'],
    ARRAY['Fruits can be used fresh or dried for utensils.'],
    ARRAY['Fruits']
),
-- 9. Elephant Ear
(
    'Elephant Ear',
    'Taro',
    'Colocasia esculenta',
    'A tropical plant with massive leaves, often used ornamentally or grown for its edible roots.',
    'Southeast Asia',
    'Shrub',
    'Tropical',
    'Perennial',
    'High',
    'Clay',
    'Large',
    'Partial Shade',
    'Fast',
    'Backyard corner, large pots',
    'Moderate',
    'https://i0.wp.com/littleprinceplants.com/wp-content/uploads/2022/01/Colocasia-esculenta-Black-Magic-scaled.jpg?fit=2560%2C2560&ssl=1',
    'Rainy/Monsoon',
    'Provide ample water and rich soil; harvest roots in fall.',
    'Prune regularly',
    5.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(22, 35),
    ARRAY['Snails', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Banana', 'Ginger'],
    ARRAY['Dry-soil plants'],
    ARRAY['Needs moisture-retentive soil.'],
    ARRAY['Leaves resemble elephant ears, hence the name.'],
    ARRAY['Corms', 'Leaves (cooked)']
),
-- 10. Sedum
(
    'Sedum',
    'Stonecrop',
    'Sedum spurium',
    'A drought-tolerant succulent perfect for groundcover and green roofs.',
    'Northern Hemisphere',
    'Succulent',
    'Temperate',
    'Perennial',
    'Low',
    'Sandy',
    'Small',
    'Full Sun',
    'Slow',
    'Green roofs, rock gardens',
    'Easy',
    'https://www.perennialco.com/product_images/uploaded_images/zsedspne0001g.jpg',
    'Spring',
    'Remove dead stems and flowers for tidiness.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(10, 25),
    ARRAY['Mealybugs'],
    ARRAY['None'],
    ARRAY['Lavender', 'Echinacea'],
    ARRAY['Wet-soil plants'],
    ARRAY['Avoid overwatering; thrives on neglect.'],
    ARRAY['Used for erosion control and on rooftops.'],
    ARRAY['Leaves']
),
-- 4. Neem
(
    'Neem',
    'Indian Lilac',
    'Azadirachta indica',
    'A fast-growing tree known for its medicinal properties and pest-repelling abilities.',
    'Indian Subcontinent',
    'Tree',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Backyard, avenue',
    'Moderate',
    'https://assets-news.housing.com/news/wp-content/uploads/2023/01/25020958/Teak-tree-shutterstock_1868125927-1200x700-compressed.jpg',
    'Spring',
    'Prune to shape and remove dead branches.',
    'Prune to shape',
    2.0,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 40),
    ARRAY['None'],
    ARRAY['None'],
    ARRAY['None'],
    ARRAY['None'],
    ARRAY['Leaves and oil are natural insect repellents.'],
    ARRAY['Used in traditional medicine for various ailments.'],
    ARRAY['Leaves', 'Seeds']
),
-- 5. Hibiscus
(
    'Hibiscus',
    'Shoe Flower',
    'Hibiscus rosa-sinensis',
    'A tropical flowering plant with large, colorful blooms.',
    'Asia',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Garden beds, pots',
    'Easy',
    'https://images.unsplash.com/photo-1613764670482-4bbbfb09b389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHwzNS4lMjBIaWJpc2N1c3xlbnwwfHx8fDE3NDUyMjExNjJ8MA&ixlib=rb-4.0.3&q=80&w=1080',
    'Spring',
    'Prune after flowering to maintain shape.',
    'Prune after bloom',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Leaf spot'],
    ARRAY['Marigold', 'Basil'],
    ARRAY['None'],
    ARRAY['Regular pruning encourages more blooms.'],
    ARRAY['Flowers are used in hair care products.'],
    ARRAY['Flowers']
),
-- 1. Tulsi
(
    'Tulsi',
    'Holy Basil',
    'Ocimum tenuiflorum',
    'A sacred plant in Hindu belief, known for its medicinal properties.',
    'Indian Subcontinent',
    'Herb',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Full Sun',
    'Moderate',
    'Balcony, courtyard',
    'Easy',
    'https://images.unsplash.com/photo-1589706261424-03debaed31ea?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Regularly pinch off flower buds to encourage leaf growth.',
    'Prune regularly',
    0.5,
    7,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Powdery mildew'],
    ARRAY['Tomato', 'Pepper'],
    ARRAY['None'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Considered sacred and used in religious rituals.'],
    ARRAY['Leaves']
),
-- 2. Curry Leaf
(
    'Curry Leaf',
    'Kadi Patta',
    'Murraya koenigii',
    'A tropical tree whose leaves are used in Indian cooking for flavor.',
    'India',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Sandy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Kitchen garden, pots',
    'Moderate',
    'https://www.getsview.com/market/wp-content/uploads/sites/8/2020/10/Curry-Leaf-Plant-For-Sale-GETSVIEW-Market.jpg',
    'Spring',
    'Prune regularly to encourage bushy growth.',
    'Prune regularly',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Scales', 'Aphids'],
    ARRAY['Leaf spot'],
    ARRAY['Chili', 'Tomato'],
    ARRAY['None'],
    ARRAY['Use neem oil to control pests organically.'],
    ARRAY['Leaves are aromatic and used in various cuisines.'],
    ARRAY['Leaves']
),
-- 1. Ixora
(
    'Ixora',
    'Jungle Geranium',
    'Ixora coccinea',
    'A dense, multi-branched evergreen shrub with vibrant flower clusters.',
    'India',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Garden beds, borders',
    'Easy',
    'https://mygreenyard.co.in/wp-content/uploads/2021/08/TT1-scaled.jpeg',
    'Spring',
    'Deadhead spent flowers to encourage continuous blooming.',
    'Prune regularly',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Mealybugs'],
    ARRAY['Leaf spot'],
    ARRAY['Marigold', 'Basil'],
    ARRAY['None'],
    ARRAY['Regular pruning encourages more blooms.'],
    ARRAY['Flowers are used in traditional medicine.'],
    ARRAY['Flowers']
),
-- 4. Golden Pothos
(
    'Golden Pothos',
    'Devils Ivy',
    'Epipremnum aureum',
    'A hardy vine with heart-shaped leavesand is ideal for hanging baskets.',
    'Solomon Islands',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Low',
    'Loamy',
    'Medium',
    'Indirect Light',
    'Fast',
    'Hanging baskets',
    'Easy',
    'https://sentinel.nl/wp-content/webp-express/webp-images/uploads/2021/03/Golden-Pothos-pot-groot.png.webp',
    'Spring',
    'Trim regularly to control growth and encourage bushiness.',
    'Prune regularly',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 30),
    ARRAY['Mealybugs', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Peace Lily', 'Snake Plant'],
    ARRAY['Overwatered plants'],
    ARRAY['Allow soil to dry between waterings.'],
    ARRAY['Excellent for beginners due to its resilience.'],
    ARRAY['None']
),
-- 2. Lantana Camara
(
    'Lantana Camara',
    'Wild Sage',
    'Lantana camara',
    'A flowering shrub with clusters of brightly colored flowers.',
    'Central and South America',
    'Shrub',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds',
    'Easy',
    'https://i0.wp.com/www.greensouq.ae/wp-content/uploads/2017/11/lantana-red-1.jpeg?resize=1200%2C1200&ssl=1',
    'Spring',
    'Prune regularly to maintain shape and encourage blooming.',
    'Prune regularly',
    0.0,
    0,
    0,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Powdery mildew'],
    ARRAY['Marigold', 'Basil'],
    ARRAY['None'],
    ARRAY['Avoid overwatering and prefers dry conditions.'],
    ARRAY['Attracts butterflies and other pollinators.'],
    ARRAY['None']
),
-- 3. Olive Tree
(
    'Olive Tree',
    'European Olive',
    'Olea europaea',
    'A small tree cultivated for its fruit and oil.',
    'Mediterranean Basin',
    'Tree',
    'Mediterranean',
    'Perennial',
    'Low',
    'Chalky',
    'Large',
    'Full Sun',
    'Slow',
    'Backyard, large pots',
    'Moderate',
    'https://www.gurneys.com/cdn/shop/files/80884A.webp?v=1729088657&width=800',
    'Spring',
    'Prune to shape and remove dead branches.',
    'Prune to shape',
    2.0,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(15, 30),
    ARRAY['Scale insects', 'Olive fruit fly'],
    ARRAY['Peacock spot'],
    ARRAY['Lavender', 'Rosemary'],
    ARRAY['High water-demanding plants'],
    ARRAY['Ensure well-drained soil to prevent root diseases.'],
    ARRAY['Symbol of peace and prosperity.'],
    ARRAY['Fruits']
),
-- 4. Kangaroo Paw
(
    'Kangaroo Paw',
    'Anigozanthos',
    'Anigozanthos flavidus',
    'A unique flowering plant with tubular flowers resembling kangaroo paws.',
    'Australia',
    'Flower',
    'Mediterranean',
    'Perennial',
    'Moderate',
    'Sandy',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds, borders',
    'Moderate',
    'https://i0.wp.com/littleprinceplants.com/wp-content/uploads/Anigozanthos-Bush-Tango-September-Bloom2-scaled.jpg?resize=768%2C768&ssl=1',
    'Spring',
    'Remove spent flowers to encourage new blooms.',
    'Prune after bloom',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['Aphids', 'Snails'],
    ARRAY['Ink spot disease'],
    ARRAY['Lavender', 'Sage'],
    ARRAY['High humidity plants'],
    ARRAY['Avoid overhead watering to prevent fungal diseases.'],
    ARRAY['Attracts hummingbirds and other pollinators.'],
    ARRAY['None']
),
-- 5. African Violet
(
    'African Violet',
    'Saintpaulia',
    'Saintpaulia ionantha',
    'A popular indoor plant known for its colorful, velvety flowers.',
    'Tanzania',
    'Flower',
    'Tropical',
    'Perennial',
    'Moderate',
    'Peaty',
    'Small',
    'Indirect Light',
    'Moderate',
    'Living rooms, offices',
    'Easy',
    'https://b3261022.smushcdn.com/3261022/wp-content/uploads/2022/10/How-Big-Do-African-Violets-Get1.jpg?lossy=1&strip=1&webp=1',
    'Spring',
    'Remove dead flowers and leaves to encourage growth.',
    'Prune after bloom',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs', 'Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Peace Lily', 'Snake Plant'],
    ARRAY['Direct sunlight plants'],
    ARRAY['Avoid water on leaves to prevent spotting.'],
    ARRAY['Flowers come in various colors and patterns.'],
    ARRAY['None']
),
-- 2. Spinach
(
    'Spinach',
    'Palak',
    'Spinacia oleracea',
    'A leafy green vegetable high in iron and vitamins.',
    'Persia',
    'Vegetable',
    'Temperate',
    'Annual',
    'High',
    'Loamy',
    'Small',
    'Partial Shade',
    'Fast',
    'Pots, containers',
    'Easy',
    'https://images.unsplash.com/photo-1592419391068-9bd09dd58510?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHw0NC4lMjBTcGluYWNofGVufDB8fHx8MTc0NTIyMTE3M3ww&ixlib=rb-4.0.3&q=80&w=1080',
    'Winter',
    'Harvest leaves regularly to encourage new growth.',
    'No pruning required',
    1.0,
    7,
    45,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Leaf miners'],
    ARRAY['Downy mildew'],
    ARRAY['Radish', 'Strawberries'],
    ARRAY['Potatoes'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Rich in iron and essential nutrients.'],
    ARRAY['Leaves']
),
-- 3. Radish
(
    'Radish',
    'Mooli',
    'Raphanus sativus',
    'A root vegetable known for its crisp texture and peppery flavor.',
    'Southeast Asia',
    'Vegetable',
    'Temperate',
    'Annual',
    'Moderate',
    'Sandy',
    'Small',
    'Full Sun',
    'Fast',
    'Containers, raised beds',
    'Easy',
    'https://gardeningsg.nparks.gov.sg/images/Plants/Radish_JacChua%20(1).jpg',
    'Winter',
    'Thin seedlings to allow proper root development.',
    'No pruning required',
    1.5,
    5,
    30,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Root maggots'],
    ARRAY['Clubroot'],
    ARRAY['Carrots', 'Lettuce'],
    ARRAY['Hyacinth'],
    ARRAY['Rotate crops to prevent soil-borne diseases.'],
    ARRAY['Quick-growing crop, ready in a month.'],
    ARRAY['Roots']
),
-- 4. Eggplant
(
    'Eggplant',
    'Brinjal',
    'Solanum melongena',
    'A versatile vegetable used in various cuisines.',
    'India',
    'Vegetable',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Pots, garden beds',
    'Moderate',
    'https://images.unsplash.com/photo-1528825950832-560a4a11473a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHw0Ni4lMjBFZ2dwbGFudHxlbnwwfHx8fDE3NDUyMjExNzV8MA&ixlib=rb-4.0.3&q=80&w=1080',
    'Summer',
    'Stake plants to support heavy fruits; prune lower leaves.',
    'Prune regularly',
    1.0,
    10,
    85,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Flea beetles'],
    ARRAY['Verticillium wilt'],
    ARRAY['Beans', 'Marigold'],
    ARRAY['Potatoes'],
    ARRAY['Use neem oil to deter pests organically.'],
    ARRAY['Rich in antioxidants and fiber.'],
    ARRAY['Fruits']
),
-- 5. Okra
(
    'Okra',
    'Lady Finger',
    'Abelmoschus esculentus',
    'A warm-season vegetable known for its edible green pods.',
    'Africa',
    'Vegetable',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Pots, garden beds',
    'Easy',
    'https://www.marthastewart.com/thmb/lMiU4yMisX2kBcIrj2CEm_J1jH4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Okra-ab374adabb95461d9eb323e0e13ad12c.jpg',
    'Summer',
    'Harvest pods when young and tender; regular picking encourages production.',
    'No pruning required',
    1.0,
    7,
    60,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Powdery mildew'],
    ARRAY['Basil', 'Cucumbers'],
    ARRAY['Onions'],
    ARRAY['Ensure proper spacing to reduce disease risk.'],
    ARRAY['High in fiber and vitamin C.'],
    ARRAY['Fruits']
),
-- 1. Dahlia
(
    'Dahlia',
    'Georgina',
    'Dahlia pinnata',
    'A vibrant flowering plant with a wide range of colors and forms.',
    'Mexico',
    'Flower',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Moderate',
    'https://stacyling.com/wp-content/uploads/2024/10/dahlias-fall-1024-4.jpg',
    'Spring',
    'Deadhead spent blooms to encourage continuous flowering.',
    'Prune after bloom',
    2.0,
    7,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['Aphids', 'Slugs'],
    ARRAY['Powdery mildew'],
    ARRAY['Marigold', 'Zinnia'],
    ARRAY['None'],
    ARRAY['Provide staking for taller varieties to prevent flopping.'],
    ARRAY['National flower of Mexico; tubers are edible but not commonly consumed.'],
    ARRAY['None']
),
-- 2. Hydrangea
(
    'Hydrangea',
    'Hortensia',
    'Hydrangea macrophylla',
    'A shrub known for its large, colorful flower heads that can change color based on soil pH.',
    'Japan',
    'Shrub',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Partial Shade',
    'Moderate',
    'Garden beds, borders',
    'Moderate',
    'https://m.media-amazon.com/images/I/61xwtpOPh-L._AC_US750_.jpg',
    'Spring',
    'Prune after flowering to maintain shape and encourage new growth.',
    'Prune after bloom',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(10, 25),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Leaf spot'],
    ARRAY['Hosta', 'Ferns'],
    ARRAY['Full sun plants'],
    ARRAY['Mulch to retain soil moisture and regulate temperature.'],
    ARRAY['Flower color can vary from blue to pink depending on soil acidity.'],
    ARRAY['None']
),
-- 4. Sunflower
(
    'Sunflower',
    'Helianthus',
    'Helianthus annuus',
    'Tall annual plant known for its large, bright yellow flower heads that follow the sun.',
    'North America',
    'Flower',
    'Temperate',
    'Annual',
    'Moderate',
    'Loamy',
    'Large',
    'Full Sun',
    'Fast',
    'Backyards, borders',
    'Easy',
    'https://images.unsplash.com/photo-1542801204-141ec23989d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHw1MC4lMjBTdW5mbG93ZXJ8ZW58MHx8fHwxNzQ1MjIxMTc5fDA&ixlib=rb-4.0.3&q=80&w=1080',
    'Spring',
    'Provide support for taller varieties to prevent lodging.',
    'Prune to shape',
    2.5,
    7,
    90,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Caterpillars'],
    ARRAY['Downy mildew'],
    ARRAY['Corn', 'Squash'],
    ARRAY['Potatoes'],
    ARRAY['Rotate crops to prevent soil-borne diseases.'],
    ARRAY['Seeds are edible and rich in nutrients.'],
    ARRAY['Seeds']
),
-- 1. Bougainvillea
(
    'Bougainvillea',
    'Paper Flower',
    'Bougainvillea glabra',
    'A vibrant climber with papery bracts in various colors.',
    'South America',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Walls, trellises',
    'Moderate',
    'https://eureka-farms.com/cdn/shop/files/Barbara_Karst_SSR.jpg?v=1742266737&width=1100',
    'Spring',
    'Prune after flowering to maintain shape and encourage blooming.',
    'Prune after bloom',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(20, 35),
    ARRAY['Aphids', 'Caterpillars'],
    ARRAY['Leaf spot'],
    ARRAY['Marigold', 'Lavender'],
    ARRAY['High water-demanding plants'],
    ARRAY['Avoid overwatering; prefers dry conditions.'],
    ARRAY['Known for its vibrant bracts and drought tolerance.'],
    ARRAY['None']
),
-- 2. Geranium
(
    'Geranium',
    'Cranesbill',
    'Pelargonium spp.',
    'A popular flowering plant with clusters of colorful blooms.',
    'South Africa',
    'Flower',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Containers, borders',
    'Easy',
    'https://www.organicindiaseeds.com/cdn/shop/files/geranium-pelargonium-bonsai-flower-seeds-for-planting-100-pcs-598.webp?v=1728559463&width=1000',
    'Spring',
    'Deadhead spent flowers to encourage continuous blooming.',
    'Prune regularly',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 25),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Botrytis blight'],
    ARRAY['Marigold', 'Lavender'],
    ARRAY['High humidity plants'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Known for its fragrant leaves and vibrant flowers.'],
    ARRAY['Leaves']
),
-- 3. Hibiscus
(
    'Hibiscus',
    'Rose Mallow',
    'Hibiscus rosa-sinensis',
    'A tropical shrub with large, colorful flowers.',
    'Asia',
    'Shrub',
    'Tropical',
    'Perennial',
    'High',
    'Loamy',
    'Large',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Moderate',
    'https://images.unsplash.com/photo-1613764670482-4bbbfb09b389?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&',
    'Summer',
    'Prune to shape and remove dead or weak branches.',
    'Prune regularly',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Leaf spot'],
    ARRAY['Marigold', 'Basil'],
    ARRAY['High water-demanding plants'],
    ARRAY['Regular pruning encourages more blooms.'],
    ARRAY['National flower of several countries.'],
    ARRAY['Flowers']
),
-- 4. Zinnia
(
    'Zinnia',
    'Youth-and-age',
    'Zinnia elegans',
    'An annual plant with bright, daisy-like flowers.',
    'Mexico',
    'Flower',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Easy',
    'https://www.applewoodseed.com/wp-content/uploads/2017/01/Zinnia-Meteor-ZEME-1601-705x680.jpg',
    'Spring',
    'Deadhead regularly to promote continuous blooming.',
    'Prune regularly',
    0.5,
    7,
    60,
    TRUE,
    FALSE,
    FALSE,
    numrange(20, 35),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Powdery mildew'],
    ARRAY['Marigold', 'Basil'],
    ARRAY['High humidity plants'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Attracts butterflies and other pollinators.'],
    ARRAY['None']
),
-- 5. Cosmos
(
    'Cosmos',
    'Cosmea',
    'Cosmos bipinnatus',
    'A tall annual with feathery foliage and colorful blooms.',
    'Mexico',
    'Flower',
    'Tropical',
    'Annual',
    'Low',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Garden beds, borders',
    'Easy',
    'https://images.unsplash.com/photo-1602673452284-3cb89982e9bb?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'Spring',
    'Deadhead spent flowers to encourage more blooms.',
    'Prune regularly',
    0.5,
    7,
    70,
    TRUE,
    FALSE,
    FALSE,
    numrange(20, 35),
    ARRAY['Aphids', 'Thrips'],
    ARRAY['Powdery mildew'],
    ARRAY['Marigold', 'Lavender'],
    ARRAY['High humidity plants'],
    ARRAY['Avoid overwatering; prefers dry conditions.'],
    ARRAY['Attracts bees and butterflies.'],
    ARRAY['None']
),
-- 2. Geranium
(
    'Geranium',
    'Cranesbill',
    'Pelargonium spp.',
    'A popular flowering plant with clusters of colorful blooms.',
    'South Africa',
    'Flower',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Containers, borders',
    'Easy',
    'https://www.organicindiaseeds.com/cdn/shop/files/geranium-pelargonium-bonsai-flower-seeds-for-planting-100-pcs-598.webp?v=1728559463&width=1000',
    'Spring',
    'Deadhead spent flowers to encourage continuous blooming.',
    'Prune regularly',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(15, 25),
    ARRAY['Aphids', 'Whiteflies'],
    ARRAY['Botrytis blight'],
    ARRAY['Marigold', 'Lavender'],
    ARRAY['High humidity plants'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Known for its fragrant leaves and vibrant flowers.'],
    ARRAY['Leaves']
),
-- 1. Morning Glory
(
    'Morning Glory',
    'Ipomoea',
    'Ipomoea purpurea',
    'A fast-growing vine with trumpet-shaped flowers that bloom in the morning.',
    'Central America',
    'Climber/Vine',
    'Tropical',
    'Annual',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Veranda railing, hanging pots',
    'Easy',
    'https://i0.wp.com/www.satvai.com/wp-content/uploads/2018/04/1522807416468.jpg?w=600&ssl=1',
    'Spring',
    'Provide a trellis or support; self-seeds easily.',
    'Prune to shape',
    1.0,
    7,
    70,
    TRUE,
    FALSE,
    FALSE,
    numrange(20, 35),
    ARRAY['Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Nasturtium', 'Marigold'],
    ARRAY['None'],
    ARRAY['Flowers attract butterflies and bees.'],
    ARRAY['Blooms fade by noon.'],
    ARRAY['None']
),
-- 2. Rangoon Creeper
(
    'Rangoon Creeper',
    'Madhumalti',
    'Quisqualis indica',
    'A fragrant flowering vine with color-changing blooms from white to red.',
    'Southeast Asia',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Moderate',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Veranda wall, trellis',
    'Moderate',
    'https://lovemyplants.in/wp-content/uploads/2023/11/RANGOON-CREEPER.jpg',
    'Spring',
    'Train onto vertical supports; prune to prevent overgrowth.',
    'Prune regularly',
    1.5,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids'],
    ARRAY['Leaf spot'],
    ARRAY['Bougainvillea'],
    ARRAY['Cactus'],
    ARRAY['Keep roots moist; mulch helps retain water.'],
    ARRAY['Flowers change color with age.'],
    ARRAY['Flowers']
),
-- 3. Bleeding Heart Vine
(
    'Bleeding Heart Vine',
    'Glorybower',
    'Clerodendrum thomsoniae',
    'A woody vine with showy red and white flower clusters, ideal for small trellises.',
    'West Africa',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Veranda corner trellis',
    'Moderate',
    'https://agrogreeninfotech.com/wp-content/uploads/2022/12/Bleeding-Heart-Vine-White-.jpg',
    'Spring',
    'Pinch back tips to encourage bushier growth.',
    'Prune to shape',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(18, 30),
    ARRAY['Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Ferns', 'Peace Lily'],
    ARRAY['Direct sunlight'],
    ARRAY['Prefers high humidity and indirect light.'],
    ARRAY['Named for the heart-shaped flower pattern.'],
    ARRAY['None']
),
-- 4. Jasmine
(
    'Jasmine',
    'Mogra',
    'Jasminum sambac',
    'A sweet-scented vine/bush with white blooms popular in South Asian homes.',
    'South Asia',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Partial Shade',
    'Moderate',
    'Veranda pots, ledges',
    'Easy',
    'https://hips.hearstapps.com/hmg-prod/images/star-jasmine-in-the-rain-royalty-free-image-1720728061.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*',
    'Summer',
    'Prune regularly to keep compact; remove faded blooms.',
    'Prune regularly',
    0.5,
    10,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(22, 35),
    ARRAY['Aphids'],
    ARRAY['Sooty mold'],
    ARRAY['Marigold', 'Tulsi'],
    ARRAY['Wet-loving plants'],
    ARRAY['Dont let water sit on leaves.'],
    ARRAY['Used in perfumes and religious rituals.'],
    ARRAY['Flowers']
),
-- 6. Chinese Hat Plant
(
    'Chinese Hat Plant',
    'Holmskioldia',
    'Holmskioldia sanguinea',
    'An unusual shrub/vine with cup-shaped orange-red flowers.',
    'Himalayas',
    'Shrub',
    'Subtropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Veranda edge, railing',
    'Moderate',
    'https://i0.wp.com/greencoverinitiative.com/wp-content/uploads/2024/08/Chinese-hat-plant1a-1.jpg?w=600&ssl=1',
    'Spring',
    'Cut back after flowering to maintain shape.',
    'Prune after bloom',
    1.0,
    14,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 30),
    ARRAY['Caterpillars'],
    ARRAY['Rust'],
    ARRAY['Zinnia', 'Cosmos'],
    ARRAY['Overwatered pots'],
    ARRAY['Needs occasional hard pruning.'],
    ARRAY['Shaped like tiny hats.'],
    ARRAY['None']
),
-- 7. Crossandra
(
    'Crossandra',
    'Firecracker Flower',
    'Crossandra infundibuliformis',
    'Compact bushy plant with bright orange blooms ideal for container gardens.',
    'India',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Partial Shade',
    'Moderate',
    'Veranda pots, balcony shelves',
    'Easy',
    'https://tropicalplantsofflorida.com/wp-content/uploads/Crossandra-Plant.jpg',
    'Spring',
    'Pinch off dead flowers and trim for shape.',
    'Prune regularly',
    0.5,
    10,
    0,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 35),
    ARRAY['Aphids'],
    ARRAY['Leaf spot'],
    ARRAY['Jasmine', 'Lavender'],
    ARRAY['Mint'],
    ARRAY['Prefers filtered sunlight.'],
    ARRAY['Flowers resemble a firework burst.'],
    ARRAY['None']
),
-- 2. Vetiver
(
    'Vetiver',
    'Khus Grass',
    'Chrysopogon zizanioides',
    'A deep-rooted grass used in perfumery and soil erosion control.',
    'India',
    'Grass',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Full Sun',
    'Slow',
    'Slopes, roof beds, pots',
    'Moderate',
    'https://www.gardenia.net/wp-content/uploads/2023/05/chrysopogon-zizanioides-780x520.webp',
    'Spring',
    'Harvest roots annually; keep trimmed to control size.',
    'Prune to shape',
    1.0,
    21,
    365,
    FALSE,
    FALSE,
    TRUE,
    numrange(25, 40),
    ARRAY['None'],
    ARRAY['Root rot'],
    ARRAY['Lemongrass', 'Marigold'],
    ARRAY['Mint'],
    ARRAY['Avoid waterlogging.'],
    ARRAY['Used in natural cooling mats and oils.'],
    ARRAY['Roots']
),
-- 3. Fountain Grass
(
    'Fountain Grass',
    'Crimson Fountain',
    'Pennisetum setaceum',
    'Ornamental grass with burgundy plumes and arching foliage.',
    'Africa',
    'Grass',
    'Subtropical',
    'Perennial',
    'Moderate',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Pots, borders, rooftop',
    'Easy',
    'https://troystropics.com/wp-content/uploads/2022/09/red-fountain-grass.jpg',
    'Spring',
    'Cut back to base annually for regrowth.',
    'Prune annually',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(15, 30),
    ARRAY['None'],
    ARRAY['Leaf scorch'],
    ARRAY['Lavender', 'Zinnia'],
    ARRAY['Wet-soil plants'],
    ARRAY['Trim old growth in spring.'],
    ARRAY['Wavy texture creates movement in wind.'],
    ARRAY['None']
),
-- 4. Japanese Blood Grass
(
    'Japanese Blood Grass',
    'Imperata',
    'Imperata cylindrica',
    'A striking red-tipped ornamental grass ideal for containers.',
    'East Asia',
    'Grass',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Moderate',
    'Balcony pots, edge beds',
    'Easy',
    'https://cdn.mos.cms.futurecdn.net/dsKrNTMTEhBTjmcWYbWMPZ-1254-80.jpg.webp',
    'Spring',
    'Cut back in late winter.',
    'Prune to shape',
    0.5,
    14,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(15, 28),
    ARRAY['None'],
    ARRAY['Rust'],
    ARRAY['Succulents'],
    ARRAY['Mint'],
    ARRAY['Grows well in pots.'],
    ARRAY['Turns bright red in summer-fall.'],
    ARRAY['None']
),
-- 5. Dwarf Mondo Grass
(
    'Dwarf Mondo Grass',
    'Ophiopogon',
    'Ophiopogon japonicus',
    'Low-growing grass-like groundcover for shaded verandas.',
    'Japan',
    'Grass',
    'Temperate',
    'Perennial',
    'Moderate',
    'Silty',
    'Small',
    'Partial Shade',
    'Slow',
    'Veranda pots, between pavers',
    'Easy',
    'https://i0.wp.com/littleprinceplants.com/wp-content/uploads/2020/09/Ophiopogon-Pam-Harper-Variegated-Mondo-Grass-scaled.jpg?resize=768%2C768&ssl=1',
    'Spring',
    'Trim old leaves once a year.',
    'Prune annually',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(15, 25),
    ARRAY['Slugs'],
    ARRAY['Root rot'],
    ARRAY['Ferns', 'Hostas'],
    ARRAY['Sun-lovers'],
    ARRAY['Perfect for shaded balcony floors.'],
    ARRAY['Sometimes blooms with tiny lavender flowers.'],
    ARRAY['None']
),
-- 6. Baby Panda Grass
(
    'Baby Panda Grass',
    'Pogonatherum',
    'Pogonatherum paniceum',
    'A cute, compact ornamental grass perfect for pots.',
    'Asia',
    'Grass',
    'Tropical',
    'Perennial',
    'High',
    'Loamy',
    'Small',
    'Partial Shade',
    'Moderate',
    'Window boxes, desk pots',
    'Easy',
    'https://www.thetutuguru.com.au/wp-content/uploads/2024/07/Pogonatherum-Baby-Panda-Bamboo-Pot.jpg',
    'Spring',
    'Trim lightly as needed.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(20, 30),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Peace Lily', 'Calathea'],
    ARRAY['Cactus'],
    ARRAY['Avoid direct harsh sun.'],
    ARRAY['Adored for mini panda-like tufts.'],
    ARRAY['None']
),
-- 7. Chinese Evergreen
(
    'Chinese Evergreen',
    'Aglaonema',
    'Aglaonema commutatum',
    'A popular indoor plant known for its attractive variegated leaves and low maintenance.',
    'Southeast Asia',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Peaty',
    'Medium',
    'Indirect Light',
    'Slow',
    'Living room, office',
    'Easy',
    'https://www.ikea.com/gb/en/images/products/aglaonema-potted-plant__1220752_pe913524_s5.jpg?f=xl',
    'Spring',
    'Remove yellowing leaves to maintain appearance.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Peace Lily', 'Pothos'],
    ARRAY['Direct sunlight'],
    ARRAY['Keep away from cold drafts and direct sun.'],
    ARRAY['Known for its air-purifying qualities.'],
    ARRAY['None']
),
-- 8. Rubber Plant
(
    'Rubber Plant',
    'Indian Rubber Tree',
    'Ficus elastica',
    'A large indoor plant with glossy, dark green leaves.',
    'India',
    'Tree',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Bright Indirect Light',
    'Moderate',
    'Living room corners',
    'Easy',
    'https://abeautifulmess.com/wp-content/uploads/2023/06/rubbertree-1-1122x1536.jpg',
    'Spring',
    'Wipe leaves regularly to remove dust.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Scale insects', 'Mealybugs'],
    ARRAY['Leaf drop'],
    ARRAY['Snake Plant', 'ZZ Plant'],
    ARRAY['Cold drafts'],
    ARRAY['Allow soil to dry between waterings.'],
    ARRAY['Produces latex-like sap when cut.'],
    ARRAY['None']
),
-- 9. String of Pearls
(
    'String of Pearls',
    'String of Beads',
    'Senecio rowleyanus',
    'A unique succulent with trailing stems of round, bead-like leaves.',
    'South Africa',
    'Succulent',
    'Arid',
    'Perennial',
    'Low',
    'Sandy',
    'Small',
    'Bright Indirect Light',
    'Moderate',
    'Hanging baskets, shelves',
    'Moderate',
    'https://www.bhg.com/thmb/N9xZDE9lmN0KiUCShi2o9axRkZk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/BHG-How-to-Grow-and-Care-for-String-of-Pearls-Plant-101013958-ec44a47102af4e52ab067f21cc26efc2.jpg',
    'Spring',
    'Allow soil to dry completely between waterings.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Other succulents'],
    ARRAY['Overwatering'],
    ARRAY['Use well-draining soil and avoid overwatering.'],
    ARRAY['Leaves store water like tiny pearls.'],
    ARRAY['None']
),
-- 10. Bird of Paradise
(
    'Bird of Paradise',
    'Crane Flower',
    'Strelitzia reginae',
    'A stunning indoor plant with large, banana-like leaves and exotic flowers.',
    'South Africa',
    'Shrub',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Bright Indirect Light',
    'Slow',
    'Living room, conservatory',
    'Moderate',
    'https://www.thespruce.com/thmb/fDrSp4nfT6yPAxUVRb-WUomZXfs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/SPR-bird-of-paradise-plants-2132859-hero-83ba0a370f284175a229ce271790e133.jpg',
    'Spring',
    'Wipe leaves regularly to remove dust.',
    'Prune damaged leaves',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Scale insects'],
    ARRAY['Root rot'],
    ARRAY['Fiddle Leaf Fig', 'Monstera'],
    ARRAY['Cold drafts'],
    ARRAY['Keep away from cold drafts and direct sun.'],
    ARRAY['Flowers resemble exotic birds in flight.'],
    ARRAY['None']
),
-- 11. Pilea Peperomioides
(
    'Pilea Peperomioides',
    'Chinese Money Plant',
    'Pilea peperomioides',
    'A trendy houseplant with round, coin-like leaves on long stems.',
    'China',
    'Herb',
    'Temperate',
    'Perennial',
    'Moderate',
    'Loamy',
    'Small',
    'Bright Indirect Light',
    'Moderate',
    'Desk, shelves',
    'Easy',
    'https://thelittlebotanical.com/app/uploads/2023/07/Pilea3.jpg',
    'Spring',
    'Rotate regularly for even growth.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Peace Lily', 'Pothos'],
    ARRAY['Direct sunlight'],
    ARRAY['Keep soil consistently moist but not waterlogged.'],
    ARRAY['Known as the "pass it on" plant due to easy propagation.'],
    ARRAY['None']
),
-- 12. Caladium
(
    'Caladium',
    'Angel Wings',
    'Caladium bicolor',
    'A tropical plant known for its colorful, heart-shaped leaves.',
    'South America',
    'Herb',
    'Tropical',
    'Perennial',
    'High',
    'Peaty',
    'Medium',
    'Indirect Light',
    'Moderate',
    'Living room, bathroom',
    'Moderate',
    'https://www.meadowsfarms.com/great-big-greenhouse-gardening-blog/wp-content/uploads/sites/2/2019/04/caladiums-min.jpg.webp',
    'Spring',
    'Remove yellowing leaves to maintain appearance.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(20, 30),
    ARRAY['Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Ferns', 'Peace Lily'],
    ARRAY['Direct sunlight'],
    ARRAY['Maintain high humidity and indirect light.'],
    ARRAY['Leaves come in various colors and patterns.'],
    ARRAY['None']
),
-- 13. String of Hearts
(
    'String of Hearts',
    'Rosary Vine',
    'Ceropegia woodii',
    'A delicate trailing plant with heart-shaped leaves.',
    'South Africa',
    'Succulent',
    'Arid',
    'Perennial',
    'Low',
    'Sandy',
    'Small',
    'Bright Indirect Light',
    'Moderate',
    'Hanging baskets, shelves',
    'Easy',
    'https://plantlife.ie/wp-content/uploads/2020/09/cewo9816.jpg',
    'Spring',
    'Allow soil to dry between waterings.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['String of Pearls', 'Pothos'],
    ARRAY['Overwatering'],
    ARRAY['Use well-draining soil and avoid overwatering.'],
    ARRAY['Leaves resemble tiny hearts on trailing stems.'],
    ARRAY['None']
),
-- 14. Philodendron Brasil
(
    'Philodendron Brasil',
    'Heart Leaf Philodendron',
    'Philodendron hederaceum ''Brasil''',
    'A climbing plant with heart-shaped leaves featuring yellow variegation.',
    'Brazil',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Indirect Light',
    'Fast',
    'Hanging baskets, moss poles',
    'Easy',
    'https://www.thespruce.com/thmb/SFf6jeKAjMAhbLdGJ415T7Lpxrg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/heartleaf-philodendron-guide-5181702-hero-d7f06d3be69a42e2b71441e6d0d0ed86.jpg',
    'Spring',
    'Provide support for climbing; wipe leaves regularly.',
    'Prune to shape',
    0.0,
    0,
    0,
    FALSE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs', 'Spider mites'],
    ARRAY['Root rot'],
    ARRAY['Monstera', 'Pothos'],
    ARRAY['Direct sunlight'],
    ARRAY['Keep soil consistently moist but not waterlogged.'],
    ARRAY['Leaves have striking yellow variegation.'],
    ARRAY['None']
),
-- 15. Hoya
(
    'Hoya',
    'Wax Plant',
    'Hoya carnosa',
    'A vining plant known for its waxy leaves and fragrant flower clusters.',
    'Asia',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Medium',
    'Bright Indirect Light',
    'Slow',
    'Hanging baskets, trellises',
    'Easy',
    'https://www.plantandpot.nz/wp-content/uploads/2019/08/Hoya-Carnosa-Shelfie-768x768.jpg',
    'Spring',
    'Allow soil to dry between waterings.',
    'Prune to shape',
    0.0,
    0,
    0,
    TRUE,
    FALSE,
    FALSE,
    numrange(18, 24),
    ARRAY['Mealybugs'],
    ARRAY['Root rot'],
    ARRAY['Philodendron', 'Pothos'],
    ARRAY['Overwatering'],
    ARRAY['Prefers to be slightly pot-bound.'],
    ARRAY['Flowers produce sweet nectar.'],
    ARRAY['None']
),
-- 70. Kale
(
    'Kale',
    'Borecole',
    'Brassica oleracea var. sabellica',
    'A nutrient-dense leafy green vegetable perfect for garden beds and containers.',
    'Europe',
    'Vegetable',
    'Temperate',
    'Biennial',
    'Moderate',
    'Loamy',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Easy',
    'image.png',
    'Spring/Fall',
    'Harvest outer leaves regularly to promote growth.',
    'Remove yellowing leaves',
    1.0,
    7,
    50,
    FALSE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Cabbage worms', 'Aphids'],
    ARRAY['Powdery mildew'],
    ARRAY['Herbs', 'Nasturtium'],
    ARRAY['Strawberries', 'Beans'],
    ARRAY['Use companion planting to deter pests.'],
    ARRAY['One of the most nutrient-dense foods on Earth.'],
    ARRAY['Leaves']
),
-- 71. Artichoke
(
    'Artichoke',
    'Globe Artichoke',
    'Cynara cardunculus var. scolymus',
    'A striking architectural plant that produces edible flower buds.',
    'Mediterranean',
    'Vegetable',
    'Mediterranean',
    'Perennial',
    'Moderate',
    'Loamy',
    'Large',
    'Full Sun',
    'Moderate',
    'Garden beds',
    'Moderate',
    'https://homesteadandchill.com/wp-content/uploads/2023/05/how-to-grow-artichokes-guide-homestead-chill-feature-1.jpg',
    'Spring',
    'Cut back after harvest; mulch in winter.',
    'Prune annually',
    1.0,
    14,
    150,
    TRUE,
    TRUE,
    TRUE,
    numrange(15, 25),
    ARRAY['Aphids', 'Slugs'],
    ARRAY['Botrytis'],
    ARRAY['Sunflowers', 'Tarragon'],
    ARRAY['None'],
    ARRAY['Provide wind protection and good drainage.'],
    ARRAY['Flower buds are harvested before they bloom.'],
    ARRAY['Flower buds', 'Hearts']
),
-- 72. Dragon Fruit
(
    'Dragon Fruit',
    'Pitaya',
    'Hylocereus undatus',
    'A climbing cactus with spectacular flowers and exotic fruit.',
    'Central America',
    'Fruit',
    'Tropical',
    'Perennial',
    'Low',
    'Sandy',
    'Large',
    'Full Sun',
    'Fast',
    'Rooftop, large containers',
    'Moderate',
    'https://www.gardenloversclub.com/wp-content/uploads/2018/10/Dragon-fruit-tree-field.jpg',
    'Spring',
    'Provide strong support; prune to maintain size.',
    'Prune regularly',
    1.0,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Ants', 'Scale insects'],
    ARRAY['Stem rot'],
    ARRAY['Other cacti'],
    ARRAY['None'],
    ARRAY['Ensure good air circulation and drainage.'],
    ARRAY['Flowers bloom at night and last only one night.'],
    ARRAY['Fruits']
),
-- 73. Lemongrass
(
    'Lemongrass',
    'Citronella grass',
    'Cymbopogon citratus',
    'A fragrant grass used in cooking and traditional medicine.',
    'Southeast Asia',
    'Herb',
    'Tropical',
    'Perennial',
    'Low',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Easy',
    'https://example.com/lemongrass.jpg',
    'Spring',
    'Harvest stalks when pencil-thick.',
    'Divide clumps every 2-3 years',
    0.5,
    10,
    120,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 35),
    ARRAY['Spider mites', 'Rust'],
    ARRAY['Root rot'],
    ARRAY['Basil', 'Cilantro'],
    ARRAY['None'],
    ARRAY['Keep soil consistently moist but not waterlogged.'],
    ARRAY['Natural mosquito repellent properties.'],
    ARRAY['Stalks', 'Leaves']
),
-- 74. Wasabi
(
    'Wasabi',
    'Japanese Horseradish',
    'Eutrema japonicum',
    'A shade-loving plant prized for its pungent rhizome.',
    'Japan',
    'Herb',
    'Temperate',
    'Perennial',
    'High',
    'Rich, moist',
    'Small',
    'Shade',
    'Slow',
    'Indoor, shaded gardens',
    'Difficult',
    'https://images.arigatotravel.com/wp-content/uploads/2022/09/15101524/fresh-wasabi-roots.jpeg.jpg',
    'Spring',
    'Maintain high humidity and cool temperatures.',
    'Remove dead leaves',
    0.3,
    24,
    730,
    TRUE,
    TRUE,
    FALSE,
    numrange(12, 20),
    ARRAY['Slugs', 'Snails'],
    ARRAY['Crown rot'],
    ARRAY['Ferns', 'Moss'],
    ARRAY['Hot weather plants'],
    ARRAY['Requires constant moisture and shade.'],
    ARRAY['Takes 2 years to mature for harvest.'],
    ARRAY['Rhizome', 'Leaves']
),
-- 75. Finger Lime
(
    'Finger Lime',
    'Citrus caviar',
    'Citrus australasica',
    'An Australian native citrus with unique caviar-like pulp.',
    'Australia',
    'Fruit',
    'Subtropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Slow',
    'Garden beds, containers',
    'Moderate',
    'https://chefin.com/wp-content/uploads/2019/01/finger-lime.jpg',
    'Spring',
    'Protect from frost; prune to shape.',
    'Light pruning',
    1.5,
    21,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(15, 30),
    ARRAY['Citrus leaf miner', 'Scale'],
    ARRAY['Citrus canker'],
    ARRAY['Other citrus', 'Native plants'],
    ARRAY['None'],
    ARRAY['Good drainage is essential.'],
    ARRAY['Fruits contain bubble-like vesicles.'],
    ARRAY['Fruits']
),
-- 76. Passion Fruit
(
    'Passion Fruit',
    'Purple Granadilla',
    'Passiflora edulis',
    'A vigorous climbing vine with exotic flowers and delicious fruits.',
    'South America',
    'Fruit',
    'Tropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Trellis, pergola',
    'Moderate',
    'https://www.tropicalpermaculture.com/images/xgrowing-passionfruit.jpg.pagespeed.ic.IP3uXalWjv.webp',
    'Spring',
    'Provide strong support; prune to control growth.',
    'Prune annually',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Scale insects'],
    ARRAY['Fusarium wilt'],
    ARRAY['Banana', 'Guava'],
    ARRAY['None'],
    ARRAY['Ensure good air circulation to prevent fungal diseases.'],
    ARRAY['Flowers are pollinated by carpenter bees.'],
    ARRAY['Fruits']
),
-- 77. Kaffir Lime
(
    'Kaffir Lime',
    'Makrut Lime',
    'Citrus hystrix',
    'A citrus tree with distinctive double-lobed leaves used in Southeast Asian cuisine.',
    'Southeast Asia',
    'Tree',
    'Tropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Slow',
    'Garden beds, containers',
    'Moderate',
    'https://sukhothai-nola.com/wp-content/uploads/2020/07/Kaffir-Lime-Thailand-Medical-News.jpg',
    'Spring',
    'Protect from frost; prune to shape.',
    'Light pruning',
    0.5,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(15, 30),
    ARRAY['Citrus leaf miner', 'Scale'],
    ARRAY['Citrus canker'],
    ARRAY['Other citrus', 'Lemongrass'],
    ARRAY['None'],
    ARRAY['Good drainage is essential.'],
    ARRAY['Leaves are used in Thai and Indonesian cooking.'],
    ARRAY['Leaves', 'Fruits']
),
-- 78. Saffron Crocus
(
    'Saffron Crocus',
    'Autumn Crocus',
    'Crocus sativus',
    'A fall-blooming crocus that produces the world''s most expensive spice.',
    'Greece',
    'Flower',
    'Mediterranean',
    'Perennial',
    'Low',
    'Well-draining',
    'Small',
    'Full Sun',
    'Slow',
    'Garden beds, containers',
    'Moderate',
    'https://m.media-amazon.com/images/I/61w52pKpatL._SY300_SX300_QL70_FMwebp_.jpg',
    'Fall',
    'Plant in well-draining soil; harvest stigmas when flowers open.',
    'No pruning required',
    0.1,
    14,
    180,
    TRUE,
    FALSE,
    TRUE,
    numrange(10, 25),
    ARRAY['Rabbits', 'Squirrels'],
    ARRAY['Corm rot'],
    ARRAY['Lavender', 'Rosemary'],
    ARRAY['Wet-soil plants'],
    ARRAY['Ensure good drainage to prevent corm rot.'],
    ARRAY['It takes 75,000 flowers to produce one pound of saffron.'],
    ARRAY['Stigmas']
),
-- 79. Vanilla Orchid
(
    'Vanilla Orchid',
    'Vanilla Planifolia',
    'Vanilla planifolia',
    'A climbing orchid that produces vanilla beans.',
    'Mexico',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'High',
    'Rich, well-draining',
    'Large',
    'Partial Shade',
    'Slow',
    'Greenhouse, trellis',
    'Difficult',
    'https://fairchildgarden.org/wp-content/uploads/2024/02/vanilla-orchid.png',
    'Spring',
    'Maintain high humidity; hand-pollinate flowers.',
    'Prune to control growth',
    0.0,
    0,
    730,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Mealybugs', 'Scale insects'],
    ARRAY['Root rot'],
    ARRAY['Ferns', 'Moss'],
    ARRAY['Direct sunlight'],
    ARRAY['Requires high humidity and filtered light.'],
    ARRAY['Vanilla is the second most expensive spice after saffron.'],
    ARRAY['Pods']
),
-- 80. Cardamom
(
    'Cardamom',
    'Green Cardamom',
    'Elettaria cardamomum',
    'A tropical plant that produces aromatic seeds used in cooking and medicine.',
    'India',
    'Herb',
    'Tropical',
    'Perennial',
    'High',
    'Rich, well-draining',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Garden beds, containers',
    'Moderate',
    'https://thottamfarmfresh.com/wp-content/uploads/2023/06/Thottam-farm-fresh-Cardamom.webp',
    'Spring',
    'Maintain high humidity; harvest pods when green.',
    'Remove dead leaves',
    0.5,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Thrips'],
    ARRAY['Rhizome rot'],
    ARRAY['Ginger', 'Turmeric'],
    ARRAY['None'],
    ARRAY['Requires consistent moisture and partial shade.'],
    ARRAY['One of the world''s most expensive spices.'],
    ARRAY['Seeds', 'Pods']
),
-- 81. Black Pepper
(
    'Black Pepper',
    'Pepper Vine',
    'Piper nigrum',
    'A climbing vine that produces the world''s most traded spice.',
    'India',
    'Climber/Vine',
    'Tropical',
    'Perennial',
    'Moderate',
    'Rich, well-draining',
    'Large',
    'Partial Shade',
    'Moderate',
    'Trellis, pergola',
    'Moderate',
    'https://thegourmanticgarden.com/wp-content/uploads/2023/06/turmeric-thegourmanticgarden-IMG_4356.jpg',
    'Spring',
    'Provide support for climbing; harvest berries when red.',
    'Prune to control growth',
    0.5,
    14,
    365,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Mealybugs', 'Scale insects'],
    ARRAY['Foot rot'],
    ARRAY['Cardamom', 'Vanilla'],
    ARRAY['None'],
    ARRAY['Requires support for climbing and partial shade.'],
    ARRAY['In medieval Europe, pepper was worth its weight in gold.'],
    ARRAY['Berries']
),
-- 82. Turmeric
(
    'Turmeric',
    'Indian Saffron',
    'Curcuma longa',
    'A rhizomatous herbaceous perennial with bright orange rhizomes used as a spice and dye.',
    'India',
    'Herb',
    'Tropical',
    'Perennial',
    'Moderate',
    'Rich, well-draining',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://example.com/turmeric.jpg',
    'Spring',
    'Plant rhizomes horizontally; harvest after leaves die back.',
    'No pruning required',
    1.0,
    14,
    240,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 30),
    ARRAY['Rhizome weevils'],
    ARRAY['Rhizome rot'],
    ARRAY['Ginger', 'Cardamom'],
    ARRAY['None'],
    ARRAY['Requires rich soil and consistent moisture.'],
    ARRAY['Used as a natural dye and anti-inflammatory.'],
    ARRAY['Rhizomes']
),
-- 83. Galangal
(
    'Galangal',
    'Thai Ginger',
    'Alpinia galanga',
    'A rhizomatous herb with aromatic roots used in Southeast Asian cuisine.',
    'Indonesia',
    'Herb',
    'Tropical',
    'Perennial',
    'Moderate',
    'Rich, well-draining',
    'Large',
    'Partial Shade',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://cdn.shopify.com/s/files/1/0674/6973/8241/files/GalangalRedFlowerLgFormat_480x480.png?v=1727071080',
    'Spring',
    'Plant rhizomes horizontally; harvest after 10 months.',
    'Remove dead leaves',
    1.0,
    14,
    300,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 30),
    ARRAY['Rhizome weevils'],
    ARRAY['Rhizome rot'],
    ARRAY['Ginger', 'Turmeric'],
    ARRAY['None'],
    ARRAY['Requires rich soil and consistent moisture.'],
    ARRAY['Used in Thai tom yum soup and other dishes.'],
    ARRAY['Rhizomes']
),
-- 84. Kava
(
    'Kava',
    'Kava Kava',
    'Piper methysticum',
    'A tropical shrub whose roots are used to make a traditional ceremonial drink.',
    'Pacific Islands',
    'Shrub',
    'Tropical',
    'Perennial',
    'High',
    'Rich, well-draining',
    'Medium',
    'Partial Shade',
    'Moderate',
    'Garden beds, containers',
    'Moderate',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Starr_070515-7054_Piper_methysticum.jpg/500px-Starr_070515-7054_Piper_methysticum.jpg',
    'Spring',
    'Maintain high humidity; harvest roots after 3-5 years.',
    'Remove dead leaves',
    0.5,
    14,
    1095,
    TRUE,
    FALSE,
    TRUE,
    numrange(20, 30),
    ARRAY['Mealybugs', 'Scale insects'],
    ARRAY['Root rot'],
    ARRAY['Taro', 'Banana'],
    ARRAY['None'],
    ARRAY['Requires consistent moisture and partial shade.'],
    ARRAY['Used in traditional ceremonies throughout the Pacific.'],
    ARRAY['Roots']
),
-- 85. Yacon
(
    'Yacon',
    'Peruvian Ground Apple',
    'Smallanthus sonchifolius',
    'A perennial tuberous root vegetable with sweet, crunchy tubers.',
    'Andes Mountains',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Garden beds',
    'Easy',
    'https://upload.wikimedia.org/wikipedia/commons/7/78/Yacon.jpg',
    'Spring',
    'Plant tubers in spring; harvest after first frost.',
    'Remove dead foliage',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Potatoes', 'Sunflowers'],
    ARRAY['None'],
    ARRAY['Tubers become sweeter after frost.'],
    ARRAY['Tubers contain inulin, a prebiotic fiber.'],
    ARRAY['Tubers', 'Leaves (cooked)']
),
-- 86. Oca
(
    'Oca',
    'New Zealand Yam',
    'Oxalis tuberosa',
    'A perennial tuberous vegetable with colorful, tangy tubers.',
    'Andes Mountains',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Small',
    'Full Sun',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://lovelygreens.com/wp-content/uploads/2022/12/grow-new-zealand-yam.jpg',
    'Spring',
    'Plant tubers in spring; harvest after first frost.',
    'Remove dead foliage',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Potatoes', 'Yacon'],
    ARRAY['None'],
    ARRAY['Tubers become sweeter after frost.'],
    ARRAY['Tubers come in various colors including red, yellow, and purple.'],
    ARRAY['Tubers', 'Leaves (cooked)']
),
-- 87. Mashua
(
    'Mashua',
    'Tropaeolum tuberosum',
    'Tropaeolum tuberosum',
    'A climbing perennial with edible tubers and flowers.',
    'Andes Mountains',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Fast',
    'Trellis, garden beds',
    'Easy',
    'https://www.herbazest.com/imgs/c/c/0/782272/mashua.jpg',
    'Spring',
    'Provide support for climbing; harvest tubers after first frost.',
    'Remove dead foliage',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Potatoes', 'Oca'],
    ARRAY['None'],
    ARRAY['Tubers become sweeter after frost.'],
    ARRAY['Flowers are edible and have a peppery flavor.'],
    ARRAY['Tubers', 'Flowers', 'Leaves']
),
-- 88. Ulluco
(
    'Ulluco',
    'Ullucus tuberosus',
    'Ullucus tuberosus',
    'A perennial vegetable with colorful, waxy tubers.',
    'Andes Mountains',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Small',
    'Full Sun',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://fernhillnursery.com/sites/default/files/plants/ulluco/purple-2.jpg',
    'Spring',
    'Plant tubers in spring; harvest after first frost.',
    'Remove dead foliage',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Potatoes', 'Oca'],
    ARRAY['None'],
    ARRAY['Tubers come in various colors including red, yellow, and purple.'],
    ARRAY['One of the oldest cultivated plants in the Andes.'],
    ARRAY['Tubers', 'Leaves (cooked)']
),
-- 89. Achira
(
    'Achira',
    'Queensland Arrowroot',
    'Canna edulis',
    'A tropical plant with edible rhizomes and ornamental flowers.',
    'South America',
    'Vegetable',
    'Tropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Garden beds, containers',
    'Easy',
    'https://strictlymedicinalseeds.com/wp-content/uploads/2017/04/Achira_blossom_500.jpg',
    'Spring',
    'Plant rhizomes horizontally; harvest after 8-10 months.',
    'Remove dead foliage',
    1.0,
    14,
    240,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Rhizome rot'],
    ARRAY['Taro', 'Banana'],
    ARRAY['None'],
    ARRAY['Requires rich soil and consistent moisture.'],
    ARRAY['Rhizomes are high in starch and used as a thickener.'],
    ARRAY['Rhizomes', 'Flowers']
),
-- 90. Chayote
(
    'Chayote',
    'Choko',
    'Sechium edule',
    'A vigorous climbing vine with edible fruits and tubers.',
    'Mexico',
    'Vegetable',
    'Tropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Trellis, pergola',
    'Easy',
    'https://ogden_images.s3.amazonaws.com/www.motherearthgardener.com/images/2020/02/15135207/chayote-fruit-1100x735.jpg',
    'Spring',
    'Provide strong support for climbing; harvest fruits when firm.',
    'Prune to control growth',
    1.0,
    14,
    120,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Spider mites'],
    ARRAY['Powdery mildew'],
    ARRAY['Beans', 'Corn'],
    ARRAY['None'],
    ARRAY['Requires support for climbing and consistent moisture.'],
    ARRAY['Entire plant is edible, including fruits, leaves, and tubers.'],
    ARRAY['Fruits', 'Leaves', 'Tubers']
),
-- 91. Malabar Spinach
(
    'Malabar Spinach',
    'Basella',
    'Basella alba',
    'A fast-growing climbing vine with edible leaves and stems.',
    'India',
    'Vegetable',
    'Tropical',
    'Annual',
    'High',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Trellis, garden beds',
    'Easy',
    'https://images.unsplash.com/photo-1592419391068-9bd09dd58510?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MjMxOTZ8MHwxfHNlYXJjaHwxfHw5MS4lMjBNYWxhYmFyJTIwU3BpbmFjaHxlbnwwfHx8fDE3NDUyMzUyNzJ8MA&ixlib=rb-4.0.3&q=80&w=1080',
    'Spring',
    'Provide support for climbing; harvest leaves regularly.',
    'Prune to control growth',
    0.5,
    7,
    60,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Slugs'],
    ARRAY['Downy mildew'],
    ARRAY['Beans', 'Corn'],
    ARRAY['None'],
    ARRAY['Regular harvesting encourages bushier growth.'],
    ARRAY['Leaves become mucilaginous when cooked.'],
    ARRAY['Leaves', 'Stems']
),
-- 92. Okinawan Spinach
(
    'Okinawan Spinach',
    'Gynura',
    'Gynura bicolor',
    'A perennial vegetable with purple and green leaves.',
    'Okinawa',
    'Vegetable',
    'Tropical',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Medium',
    'Partial Shade',
    'Fast',
    'Garden beds, containers',
    'Easy',
    'https://arealgreenlife.com/wp-content/uploads/DSCF5073.-500px.jpg',
    'Spring',
    'Harvest leaves regularly; protect from frost.',
    'Prune to control growth',
    0.5,
    7,
    60,
    TRUE,
    TRUE,
    TRUE,
    numrange(20, 30),
    ARRAY['Aphids', 'Slugs'],
    ARRAY['Downy mildew'],
    ARRAY['Basil', 'Cilantro'],
    ARRAY['None'],
    ARRAY['Regular harvesting encourages bushier growth.'],
    ARRAY['Leaves are rich in antioxidants.'],
    ARRAY['Leaves', 'Stems']
),
-- 93. Egyptian Walking Onion
(
    'Egyptian Walking Onion',
    'Tree Onion',
    'Allium × proliferum',
    'A perennial onion that produces bulbils at the top of the stalk.',
    'Egypt',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Low',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://cdn.mos.cms.futurecdn.net/6Q5Tt5sKe4NZEgtu76Rbjm-1254-80.jpg.webp',
    'Spring/Fall',
    'Plant bulbils or bulbs; harvest green onions as needed.',
    'No pruning required',
    0.5,
    7,
    60,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Onion maggots'],
    ARRAY['Downy mildew'],
    ARRAY['Carrots', 'Beets'],
    ARRAY['Beans', 'Peas'],
    ARRAY['Plant in well-draining soil to prevent bulb rot.'],
    ARRAY['Gets its name from the way it "walks" across the garden.'],
    ARRAY['Bulbs', 'Leaves', 'Bulbils']
),
-- 94. Sunchoke
(
    'Sunchoke',
    'Jerusalem Artichoke',
    'Helianthus tuberosus',
    'A tall perennial sunflower with edible tubers.',
    'North America',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Low',
    'Well-draining',
    'Large',
    'Full Sun',
    'Fast',
    'Garden beds',
    'Easy',
    'https://silveroak.com/wp-content/uploads/2020/02/Recipe-Roasted-Sunchoke-Soup.jpg',
    'Spring',
    'Plant tubers in spring; harvest after first frost.',
    'Cut back after harvest',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Sclerotinia rot'],
    ARRAY['Beans', 'Corn'],
    ARRAY['None'],
    ARRAY['Tubers become sweeter after frost.'],
    ARRAY['Tubers contain inulin, a prebiotic fiber.'],
    ARRAY['Tubers', 'Flowers']
),
-- 95. Crosne
(
    'Crosne',
    'Chinese Artichoke',
    'Stachys affinis',
    'A perennial vegetable with crisp, nutty tubers.',
    'China',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Small',
    'Full Sun',
    'Moderate',
    'Garden beds, containers',
    'Easy',
    'https://www.organicgardener.com.au/wp-content/uploads/2015/05/Chinese%20artichokes.jpg',
    'Spring',
    'Plant tubers in spring; harvest in fall.',
    'Cut back after harvest',
    1.0,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Beans', 'Corn'],
    ARRAY['None'],
    ARRAY['Tubers are best harvested in fall.'],
    ARRAY['Tubers have a crunchy texture and nutty flavor.'],
    ARRAY['Tubers']
),
-- 96. Skirret
(
    'Skirret',
    'Sium sisarum',
    'Sium sisarum',
    'A perennial vegetable with sweet, carrot-like roots.',
    'Europe',
    'Vegetable',
    'Temperate',
    'Perennial',
    'Moderate',
    'Well-draining',
    'Medium',
    'Full Sun',
    'Moderate',
    'Garden beds',
    'Easy',
    'https://i0.wp.com/www.foodforest.garden/wp-content/uploads/2016/01/800px-mfg_0375-sium-sisarum.jpg?w=800&ssl=1',
    'Spring',
    'Plant seeds or root divisions in spring; harvest in fall.',
    'Cut back after harvest',
    0.5,
    14,
    180,
    TRUE,
    TRUE,
    TRUE,
    numrange(10, 25),
    ARRAY['Slugs', 'Aphids'],
    ARRAY['Root rot'],
    ARRAY['Carrots', 'Parsnips'],
    ARRAY['None'],
    ARRAY['Roots are best harvested in fall.'],
    ARRAY['Once a popular vegetable in medieval Europe.'],
    ARRAY['Roots', 'Leaves (cooked)']
);