name: SonarQube Analyze

on:
  push:
    branches:
      - develop-backend
      - CI/sonar-1
      - main
  pull_request:
    branches:
      - develop-backend
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'        # ← this is now required
          java-version: '21'
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'            # for generated Maven settings.xml
          server-username: '${{ github.actor }}'
          server-password: '${{ secrets.GITHUB_TOKEN }}'
          overwrite-settings: true
          job-status: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build & Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # runs clean, compile, test, etc. then the sonar analysis
          mvn -B clean verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.organization=learnathon-by-geeky-solutions \
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_solace \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


        # run: mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
